---
- name: Install rancher-cli
  shell: "curl {{rancher_cli_download_url}} | tar zx --strip-components 2 -C /usr/local/bin"
  args:
    creates: /usr/local/bin/rancher
  become: yes

- name: Set permissions rancher
  file: path=/usr/local/bin/rancher mode=0755
  become: yes
